title: "Supernihil"
title_en: "Supernihil"
email: "fremmedartet@gmail.com"
description: >-
  Supernihil is an archive of experimental audiovisual works, interactive installations, and digital artifacts. An investigation into the aesthetics of noise, data translation, and the ghosts within the machine. Based in Svendborg, Denmark.
lang: da
url: "https://supernihil.buro.earth"
github_username: sloev
twitter:
  username: supernihil
  card: summary_large_image
logo: /assets/screenshots/sekvens.gif
image: /assets/screenshots/sekvens.gif
excerpt_separator: "<!--more-->"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - post-schema.json
  - schema.md
  - todo.md
